version: '2'
networks:
  project:
services:
  project:
    build:
      context: ../../
      dockerfile: ./Docker/dev/project/Dockerfile
    image: ai/tacotron2
    volumes:
      - ../../app/:/home/docker/app/:rw
    ports:
      - "8000:8000"
      - "8898:8898"
    depends_on:
      - postgresql
      - redis
      # - mongo
    links:
      - redis:redis
      - postgresql:postgresql
      # - mongo:mongo
    networks:
      project:
        aliases:
          - project
  postgresql:
    image: mdillon/postgis:11
    volumes:
      - ../../databases/dev/postgresql/data:/var/lib/postgresql/data:rw
    # ports:
    #   - "5430:5432"
    environment:
      - POSTGRES_DB=project
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=Pr0JecT
    networks:
      project:
        aliases:
          - postgresql
  redis:
    image: redis
    volumes:
      - ../../databases/dev/redis/data:/data:rw
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    # ports:
    #  - "6300:6379"
    networks:
      project:
        aliases:
          - redis
  # mongo:
  #   image: mongo
  #   volumes:
  #   - ../../databases/dev/mongo/data:/data
  #   # ports:
  #   #   - "27017:27017"
  #   networks:
  #     project:
  #       aliases:
  #         - mongo
